version: '3.8'

services:
  php:
    build: ./docker/php
    container_name: auto_symfony_php
    volumes:
      - ./:/var/www/symfony
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      # C'est LA ligne magique. Symfony lira cette variable AVANT son propre fichier .env
      # On injecte les infos directement.
      - DATABASE_URL=mysql://app_user:app_pass@db:3306/app_db?serverVersion=10.6
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=app_pass
    depends_on:
      - db
    networks:
      - dev_net

  nginx:
    image: nginx:alpine
    container_name: auto_symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/symfony
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - dev_net

  db:
    image: mariadb:10.6
    container_name: auto_symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - dev_net

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: auto_symfony_pma
    environment:
      PMA_HOST: db
      PMA_USER: app_user
      PMA_PASSWORD: app_pass
    ports:
      - "8081:80"
    networks:
      - dev_net

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
  db_data:

networks:
  dev_net: